<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-8QIQ87H" failures="4" tests="24" name="Test" time="40.791" errors="0" timestamp="2023-06-14T14:23:21 PKT">
  <testcase classname="com.restassured.usermanagment.api.testcases.UserManagemantTest" name="Test01" time="0.05">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.asString()&amp;quot; because &amp;quot;response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.asString()" because "response" is null
at com.restassured.usermanagment.api.testcases.UserManagemantTest.Test01(UserManagemantTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test01 -->
  <testcase classname="com.restassured.usermanagment.api.testcases.UserManagemantTest" name="Test02" time="0.004">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.getStatusCode()&amp;quot; because &amp;quot;response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.getStatusCode()" because "response" is null
at com.restassured.usermanagment.api.testcases.UserManagemantTest.Test02(UserManagemantTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test02 -->
  <testcase classname="com.restassured.usermanagment.api.testcases.UserManagemantTest" name="Test03" time="1.341">
    <failure type="java.lang.AssertionError" message="expected [401] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [404]
at com.restassured.usermanagment.api.testcases.UserManagemantTest.Test03(UserManagemantTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test03 -->
  <testcase classname="com.restassured.usermanagment.api.testcases.UserManagemantTest" name="Test04" time="0.671">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.restassured.login.authentication.Login.login(Login.java:47)
at com.restassured.usermanagment.api.testcases.UserManagemantTest.Test04(UserManagemantTest.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- Test04 -->
  <testcase classname="com.restassured.usermanagment.api.testcases.UseCaseManagmentTest" name="createUsecase" time="2.015"/>
  <testcase classname="com.restassured.usermanagment.api.testcases.UseCaseManagmentTest" name="getAllUseCases" time="0.584"/>
  <testcase classname="com.restassured.usermanagment.api.testcases.UseCaseManagmentTest" name="updateUseCase" time="1.402"/>
  <testcase classname="com.restassured.demo.api.testcases.AuthApiTest" name="test_00" time="0.604"/>
  <testcase classname="com.restassured.demo.api.testcases.AuthApiTest" name="test_01" time="0.617"/>
  <testcase classname="com.restassured.demo.api.testcases.AuthApiTest" name="test_02" time="1.321"/>
  <testcase classname="com.restassured.demo.api.testcases.AuthApiTest" name="test_03" time="0.629"/>
  <testcase classname="com.restassured.demo.api.testcases.AuthApiTest" name="test_04" time="0.003"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_01" time="0.649"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_02" time="0.488"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_03" time="0.402"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_04" time="0.809"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_05" time="0.755"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_06" time="0.005"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_07" time="0.002"/>
  <testcase classname="com.restassured.demo.api.testcases.APITest" name="test_08" time="0.77"/>
  <testcase classname="com.restassured.zindgi.testcases.Z2ZTransfer" name="Z2ZTransaction" time="11.189"/>
  <testcase classname="com.restassured.google.ui.testcases.GoogleTest" name="test0Function" time="6.814"/>
  <testcase classname="com.restassured.google.ui.testcases.GoogleTest" name="test1Function" time="3.114"/>
  <testcase classname="com.restassured.google.ui.testcases.GoogleTest" name="testFunction" time="3.553"/>
  <testcase classname="com.restassured.usermanagment.api.testcases.UserManagnmentBaseClass" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
</testsuite> <!-- Test -->
