<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-24T16:26:36 PKT" name="Default suite" finished-at="2023-05-24T16:26:41 PKT" duration-ms="4662">
    <groups>
    </groups>
    <test started-at="2023-05-24T16:26:36 PKT" name="Default test" finished-at="2023-05-24T16:26:41 PKT" duration-ms="4662">
      <class name="Tests.APITest">
        <test-method signature="test_01()[pri:0, instance:Tests.APITest@6933b6c6]" started-at="2023-05-24T16:26:36 PKT" name="test_01" finished-at="2023-05-24T16:26:38 PKT" duration-ms="1427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_01 -->
        <test-method signature="test_02()[pri:0, instance:Tests.APITest@6933b6c6]" started-at="2023-05-24T16:26:38 PKT" name="test_02" finished-at="2023-05-24T16:26:39 PKT" duration-ms="955" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_02 -->
        <test-method signature="test_03()[pri:0, instance:Tests.APITest@6933b6c6]" started-at="2023-05-24T16:26:39 PKT" name="test_03" finished-at="2023-05-24T16:26:39 PKT" duration-ms="427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_03 -->
        <test-method signature="test_04()[pri:0, instance:Tests.APITest@6933b6c6]" started-at="2023-05-24T16:26:39 PKT" name="test_04" finished-at="2023-05-24T16:26:40 PKT" duration-ms="941" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [201]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at Tests.APITest.test_04(APITest.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_04 -->
        <test-method signature="test_05()[pri:0, instance:Tests.APITest@6933b6c6]" started-at="2023-05-24T16:26:40 PKT" name="test_05" finished-at="2023-05-24T16:26:41 PKT" duration-ms="828" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_05 -->
      </class> <!-- Tests.APITest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
